***CSE220 [Data Structures]***



**Book Link:** https://drive.google.com/drive/folders/1mhYUK8U6mKGiZNbV9T6p8M1ayKaoFM7H

**Linear Array**

In [ ]:
# Module/Library and user defined functions

In [83]:
# Creating an array using numpy
import numpy as np
def create_array(num):
    a = np.zeros(num) # Creating array with size given in argument
    return a
a = create_array(5)
print(a)

[0. 0. 0. 0. 0.]


In [84]:
# Iterating through an array
import numpy as np
def iterate_loop(array) :
    for index in range(array.size) :
        print (array[index])
iterate_loop(a)

0.0
0.0
0.0
0.0
0.0


In [85]:
# Resizing an array
# We can not resize an array due to its fixed memory location. But we can create a new array with new leght and copy the elements of previos array
a = np.array([1,2,3,4,5])
print(a)
# Lets create an array with a new length. Lets assume the lenght of new array is 10
b = np.zeros(10)
print(b) # Created new array with lenght of 10
# Now, we copy the elements of previous array to new array
for index in range(a.size) :
    b[index] = a[index]
print(b)

[1 2 3 4 5]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 2. 3. 4. 5. 0. 0. 0. 0. 0.]


In [7]:
# Data type declaration in numpy
import numpy as np
a = np.array([1,2,3,4,5], dtype= int)
print(a)
a = np.zeros(5, dtype= int)
print(a)

[1 2 3 4 5]
[0 0 0 0 0]


In [4]:
# Copy an array(Pass by Value)

# Creating an array using numpy
import numpy as np
def create_array(num):
    a = np.zeros(num, dtype = int) # Creating array with size given in argument with declaring data type
    return a
a = create_array(5)
print(a)
# Inputing values for array
def input_value(arr) :
    for index in range(arr.size) :
        a = int(input("Enter value: ")) 
        arr[index] = a
input_value(a)
print(a)
def copy_array(arr1):
    # arr2 = arr1.copy()   #Easy way to copy an array🥹
    arr2 = np.zeros(arr1.size, dtype = int) 
    for index in range(arr2.size) :
        arr2[index]= arr1[index]
    return arr2
b = copy_array(a)
print(b)
# Changing any values of any one of the arrays. Lets check wheather they passed by values or references
b[1] = int(input("Enter the value you want to change: "))
print(a) # The changed value didn't effect this array, thus it was passed by value
print(b)

[0 0 0 0 0]
[ 5  5  3 96  2]
[ 5  5  3 96  2]
[ 5  5  3 96  2]
[ 5  1  3 96  2]


In [31]:
# Shifting the value of an array
# (1)Right to left
a = np.array([1,2,3,4,5], dtype = int)
print(a)
def right_to_left (arr) :
    for index in range(1,arr.size) :
        arr[index-1] = arr[index]
    arr[arr.size-1] = 0
    return arr
a = right_to_left(a)
print(a)
a = np.array([1,2,3,4,5], dtype = int)
#  Left to Right
def left_to_right(arr) :
    for index in range(arr.size-1,0,-1) :
        arr[index] = arr[index-1]
    arr[0] = 0
    return arr
a = left_to_right(a)
print(a)

[1 2 3 4 5]
[2 3 4 5 0]
[0 1 2 3 4]


In [5]:
# Rotating an array
import numpy as np
a = np.array([5, 3, 9, 13, 2], dtype = int)
print(a)
# from left to right
def rotate_left(arr) :
    temp = arr[0]
    for index in range(1,arr.size) :
        arr[index-1] = arr[index]
    arr[arr.size-1] = temp
    return arr
a = rotate_left(a)
print(a)
# Right to left
a = np.array([5, 3, 9, 13, 2], dtype = int)
def rotate_right(arr) :
    temp = arr[arr.size-1]
    for index in range(arr.size-2,-1,-1) :
        arr[index+1] = arr[index]
    arr[0]= temp
    return arr
a = rotate_right(a)
print(a)
    

[ 5  3  9 13  2]
[ 3  9 13  2  5]
[ 2  5  3  9 13]


In [3]:
# Reverse an array (Out-of-place & In-place)
# Reversing an array can be implemented in two ways. First, we will create a new array with the same size as the original array and then copy the values in reverse order. The method is called out-of-the-place operation.
# However, an efficient approach might be to reverse the array in the original array. By this, we will not need to allocate extra spaces. This is known as an in-place operation. To do so we need to start swapping values from the beginning position to the end position. The idea is to swap starting value with the end value, then the second value with the second last value, and so on.
import numpy as np
# Out of place
def out_of_place(arr) :
    arr2 = np.zeros(arr.size, dtype = int)
    for index in range(arr2.size) :
        arr2[index] = arr[arr.size-index-1]
    return arr2
a = np.array([5, 3, 9, 13,8, 2], dtype = int)
a = out_of_place(a)
print(a)
# In Place
def in_place(arr) :
    for index in range(arr.size) :
        if index >= arr.size-index-1 :
            break
        else :
            temp = arr[index]
            arr[index]= arr[arr.size-1-index]
            arr[arr.size-1-index] = temp
    return arr
a = np.array([5, 3, 9, 13,8, 2], dtype = int)
a = in_place(a)
print(a)

[ 2  8 13  9  3  5]
[ 2  8 13  9  3  5]


In [8]:
#  Linear Array property: Size
def print_non_dummies(arr, size) :
    for index in range(size) :
        print(arr[index])

a = create_array(8) 
print_non_dummies(a, 5)

0
0
0
0
0


In [16]:
# Insertation
# (i) At the end
import numpy as np
def resize_array(arr, size) :
    arr2= np.zeros(size , dtype = int)
    for index in range(arr.size) :
        arr2[index] = arr[index]
    return arr2
def insert_at_the_end(arr, size, elem) :
    if size >= arr.size :
        arr= resize_array(arr, size+1)
    arr[size] = elem
    return arr
arr = create_array(5)
print(insert_at_the_end(arr,5,10))
# (ii) Anywhere
def insert_anywhere(arr, size, index, element) :
    if index <0 or index > size :
        return f"Insertation not possible"
    else :
        if size > arr.size :
            arr = resize_array(arr, arr.size+1)
    for index in range(size, index+1) :
        arr[index] = arr[index-1]

    arr[index] = element
    return arr
arr=create_array(5)
print(insert_anywhere(arr, 5, 2, 10))
        

[ 0  0  0  0  0 10]
[ 0  0 10  0  0]


In [24]:
# Deletation of an element of an array
# (i) last element
def input_value(arr) :
    for index in range(arr.size) :
        a = int(input("Enter value: ")) 
        arr[index] = a
    return arr
def delete_last_element(arr, size) :
    if size == 0 :
        return f"Delete not possible"
    else :
        arr[size-1] = 0
        return arr
arr = create_array(5)
arr = input_value(arr)
print(arr)
print(delete_last_element(arr,5))
# (ii) any element
def delete_any_element(arr, size, index) :
    if size == 0 or (index< 0 or index >= size) :
        return "Deletation not possible"
    else :
        arr[index] = 0
        return arr
arr = create_array(5)
arr = input_value(arr)
print(arr)
print(delete_any_element(arr, 5, 2)) # Value of 2nd index deleted 

[5 9 5 6 3]
[5 9 5 6 0]
[5 9 5 6 3]
[5 9 0 6 3]


**Practice Problem** from central book of CSE220

In [41]:
# Practice Problem 01
def palindrome(arr) :
    flag = True
    for index in range(arr.size) :
        if index >= arr.size-index-1 :
            break
        else :
            if arr[index] == arr[arr.size-index-1] :
                pass
            else :
                flag = False
                break
    if flag :
        return "It is a palindrome"
    else :
        return "It is not a palindrome"
size = int(input("Enter the size of array: "))
arr = create_array(size)
arr = input_value(arr)
print(arr)
print(palindrome(arr))

[1 2 3 2 1]
It is a palindrome


In [44]:
# Practice Problem 02
def reverse_print(arr, size) :
    arr2 = np.zeros(size, dtype = int)
    for index in range(size) :
        arr2[index] = arr[size-index-1]
    return arr2
arr= np.array([1, 3, 2, 5,6, 0, 0])
print(reverse_print(arr, 5))

[6 5 2 3 1]


In [52]:
# Practice Problem 03
def Merge_Arrays(arr1, arr1_ele, arr2, arr2_ele) :
    arr3 = np.zeros(arr2_ele+arr1_ele, dtype = int) 
    for index1 in range(arr1_ele) :
        arr3[index1] = arr1[index1]
    for index2 in range(arr2_ele) :
        arr3[index2+arr1_ele] = arr2[index2]
    return arr3
arr1= np.array([1, 5, 6, 0, 0])
arr2= np.array([3, 5, 2, 4, 0])
print(Merge_Arrays(arr1, 3, arr2, 4)) #Array1, Array1 size, Array2, Array2 size

[1 5 6 3 5 2 4]


**Multidimentional Array**

**2D Array**

In [73]:
# Creating a 2D array
import numpy as np
arr1 = np.zeros((2,3), dtype=int)
print(arr1.ndim) # Check dimension
# variable_name = np.zeros((row_num, column_num), dtype = data_type)
row = int(input("Enter number of rows: "))
column = int(input("Enter number of column: "))
def create_2D_array(row, column) :
    return np.zeros((row,column), dtype = int)
arr1 = create_2D_array(row, column)
print(arr1)

2
[[0 0 0]
 [0 0 0]]


In [68]:
# Iterating through 2D array including allocating the elements
def iteration_row_wise(arr1) :
    for index in range(arr1.shape[0]) : # Row
        for index1 in range(arr1.shape[1]) : # Column
            arr1[index, index1] = int(input(f"Enter {index},{index1} value of array: "))
    return arr1
row = int(input("Enter number of rows: "))
column = int(input("Enter number of column: "))
a = create_2D_array(row, column)
a = iteration_row_wise(a)
print(a)
def iteration_column_wise(arr1) :
    for index in range(arr1.shape[1]) : # Column
        for index2 in range(arr1.shape[0]) : # row
            arr1[index2, index] = int(input(f"Enter {index2},{index} value of array: "))
    return arr1
a = iteration_column_wise(a)
print(a)

[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


In [70]:
# Sum of all elements in a 2D matrix :
def array_sum(arr1) :
    sum = 0
    for index in range(arr1.shape[0]) :
        for index2 in range(arr1.shape[1]) :
            sum += arr1[index, index2]
    return sum
row = int(input("Enter number of rows: "))
column = int(input("Enter number of column: "))
a = create_2D_array(row,column)
a = iteration_column_wise(a)
print(a) 
print(array_sum(a))

[[0 2 4]
 [1 3 5]]
15


In [76]:
# Sum of every row in a 2D matrix 
def row_wise_matrix_sum (arr) :
    result = np.zeros(arr.shape[0], dtype = int)
    for index in range(arr.shape[0]) :
        sum = 0
        for index1 in range(arr.shape[1]) :
            sum += arr[index, index1]
        print(f"Sum of {index+1}th row is: {sum}")
        result[index] = sum
    return result
row = int(input("Enter number of rows: "))
column = int(input("Enter number of column: "))
a = create_2D_array(row,column)
a = iteration_row_wise(a)
print(a) 
print(row_wise_matrix_sum(a))

[[ 4  3  8]
 [ 2  5  1]
 [ 7 -1  9]
 [ 5  4 -2]]
Sum of 1th row is: 15
Sum of 2th row is: 8
Sum of 3th row is: 15
Sum of 4th row is: 7
[15  8 15  7]


In [77]:
# Sum of every column in a 2D martix
def col_wise_matrix_sum(arr) :
    result = np.zeros(arr.shape[1], dtype=int)
    for index in range(arr.shape[1]) :
        sum = 0
        for index1 in range(arr.shape[0]) :
            sum += arr[index1, index] 
        print(f"Sum of {index+1}th column is: {sum}")
        result[index] = sum
    return result

row = int(input("Enter number of rows: "))
column = int(input("Enter number of column: "))
a = create_2D_array(row,column)
a = iteration_row_wise(a)
print(a) 
print(col_wise_matrix_sum(a))

[[ 4  3  8]
 [ 2  5  1]
 [ 7 -1  9]
 [ 5  4 -2]]
Sum of 1th column is: 18
Sum of 2th column is: 11
Sum of 3th column is: 16
[18 11 16]


In [79]:
# Swap the two columns of a m x 2 matrix
def swap_2column(arr) :
    for index in range(arr.shape[0]) :
        temp = arr[index, 0]
        arr[index, 0] = arr[index, 1]
        arr[index, 1] = temp
    return arr
row = int(input("Enter number of rows: "))
column = int(input("Enter number of column: "))
a = create_2D_array(row,column)
a = iteration_row_wise(a)
print(a) 
print("After Swapping Column:\n",swap_2column(a))

[[4 3]
 [2 5]
 [7 6]]
After Swapping Column:
 [[3 4]
 [5 2]
 [6 7]]


In [82]:
# Addition of primary diagonal
def sum_primary_diagonal(arr) :
    if (arr.shape[0]) != arr.shape[1] :
        return "Not a square matrix"
    else :
        sum = 0
        for index in range(arr.shape[0]) :
            sum += arr[index,index]
        return sum
row = int(input("Enter number of rows: "))
column = int(input("Enter number of column: "))
a = create_2D_array(row,column)
a = iteration_row_wise(a)
print(a) 
print(f"Sum of primary diagonal: {sum_primary_diagonal(a)}")

[[4 3 8]
 [2 5 1]
 [7 6 9]]


18

**Random Exercise** from central book of CSE220

In [27]:
#1.1
def converter(a) :
    a = a.split()
    for index in range(len(a)) :
        a[index] = int(a[index])
    return a
a = input(f"Enter size of 2 arrays: ")
a = converter(a)
# print(a)
import numpy as np
arr1 = np.zeros(a[0], dtype = int)
arr2 = np.zeros(a[1], dtype = int)
arr1_element = input("Enter the element of arr1: ")
arr1_element = converter(arr1_element)
# print(arr1_element)
arr2_element = input("Enter the element of arr2: ")
arr2_element = converter(arr2_element)
# print(arr2_element)
def converter_array(arr, element) :
    for index in range(arr.size) :
        arr[index] = element[index]
    return arr
arr1 = converter_array(arr1, arr1_element)
# print(arr1)
arr2 = converter_array(arr2, arr2_element)
# print(arr2)

count = 0
for index in range(arr2.size) :
    count += 1
for index in range(arr1.size) :
    if arr1[index] in arr2 :
        pass
    else :
        count += 1
print(count)

7


In [40]:
#1.2
import numpy as np 
def sorting(arr) :
    pos = []
    neg = []
    for index in range(arr.size) :
        if arr[index] < 0 :
            neg.append(arr[index])
        else :
            pos.append(arr[index])
    for index in range(arr.size-len(neg)) :
        arr[index] = pos[index]
    for index in range(arr.size-len(neg), arr.size) :
        arr[index] = neg[index-len(pos)]
    return arr
N = int(input("Enter number of elements: "))
arr = np.zeros(N, dtype = int)
for index in range(arr.size) :
    arr[index] = int(input(f"Enter {index+1}th element: "))
# print(arr)
print(sorting(arr))

[ 7  9 10 11 -5 -3 -4 -1]
