In [1]:
! pip install numpy
import numpy as np

Defaulting to user installation because normal site-packages is not writeable


In [2]:
class graph:
    def __init__(self, vertex, status) : # If status == False , Undirected. If status == True, Directed
        self.no_of_vertex = vertex
        self.adjacency_matrix = np.full((vertex, vertex), 0, dtype= int)
        self.status = status
    def insertEdge(self, source, to, weight = 1 ) :
        self.adjacency_matrix[source][to] = weight
        if (self.status == False) :
            self.adjacency_matrix[to][source] = weight
    def getDegree(self, value) :
        returning = 0
        for index in range(self.no_of_vertex):
            if self.adjacency_matrix[value][index] != 0 :
                returning += 1
        return returning
    def getWeight(self, value):
        returning = 0
        for index in range(self.no_of_vertex):
            if self.adjacency_matrix[value][index] != 0 :
                returning += self.adjacency_matrix[value][index]
        return returning

In [3]:
class EdgeNode:
    def __init__(self, source, destination, weight):
        self.source = source
        self.destination = destination
        self.weight = weight
        self.next = None
class LinkedList :
    def __init__(self, vertex, status):
        self.no_of_vertex = vertex
        self.vertex_list = np.full(vertex, None, dtype=object)
        self.status = status
    def insertEdgeHelper(self, source, destination, weight):
        newE = EdgeNode(source, destination, weight)
        if self.vertex_list[source] == None:
            self.vertex_list[source] = newE
        else:
            temp = self.vertex_list[source]
            while(temp != None):
                if temp.destination == destination:
                    return
                temp = temp.next
            newE.next = self.vertex_list[source]
            self.vertex_list[source] = newE

    def insertEdge(self, src, dest, weight = 1):
        self.insertEdgeHelper(src, dest, weight)
        if not self.status:
            self.insertEdgeHelper(dest, src, weight)
    def getDegree(self, vertex):     # outDegree
        count = 0
        temp = self.vertex_list[vertex]
        while(temp != None):
            count += 1
            temp = temp.next
        return count

    def printAdjList(self):
        for i in range(self.no_of_vertex):
            temp = self.vertex_list[i]
            print(f"{i}:", end=" ")
            while temp != None:
                print(f"-> {temp.destination} (W: {temp.weight})", end=" ")
                temp = temp.next
            print()


<h1 align = "center"><b>Task 01</b></h1>

<h1 align = "center">Graph</h1>

![Task 01](https://i.ibb.co.com/LQwzJjJ/graph.png)

<h1 align = "center">Adjacency Matrix</h1>

In [4]:
def maximum_degree(graph_01):
    max = float('-inf')
    sum = 0
    for index in range(graph_01.no_of_vertex) :
        sum = graph_01.getDegree(index)
        # print(sum, index)
        if sum > max :
            max = sum
            returning_row =  index
        sum = 0

    return max, returning_row

# Driver Code
graph1 = graph(8, False)
graph1.insertEdge(0,1)
graph1.insertEdge(2,1)
graph1.insertEdge(1,3)
graph1.insertEdge(2,3)
graph1.insertEdge(4,1)
graph1.insertEdge(4,2)
graph1.insertEdge(4,3)
graph1.insertEdge(4,6)
graph1.insertEdge(5,1)
graph1.insertEdge(5,7)
graph1.insertEdge(6,7)
graph1.insertEdge(6,3)
graph1.insertEdge(6,0)
graph1.insertEdge(7,4)
graph1.insertEdge(0,7)
graph1.insertEdge(0,5)
graph1.insertEdge(2,7)
graph1.insertEdge(3,7)
print(graph1.adjacency_matrix)
x = maximum_degree(graph1)
print(f"The Vertex {x[1]} has the maximum degree having {x[0]} edges")

[[0 1 0 0 0 1 1 1]
 [1 0 1 1 1 1 0 0]
 [0 1 0 1 1 0 0 1]
 [0 1 1 0 1 0 1 1]
 [0 1 1 1 0 0 1 1]
 [1 1 0 0 0 0 0 1]
 [1 0 0 1 1 0 0 1]
 [1 0 1 1 1 1 1 0]]
The Vertex 7 has the maximum degree having 6 edges


<h1 align = "center">Adjacency List</h1>

In [5]:
graph1 = LinkedList(8, False)

graph1.insertEdge(0,1)
graph1.insertEdge(2,1)
graph1.insertEdge(1,3)
graph1.insertEdge(2,3)
graph1.insertEdge(4,1)
graph1.insertEdge(4,2)
graph1.insertEdge(4,3)
graph1.insertEdge(4,6)
graph1.insertEdge(5,1)
graph1.insertEdge(5,7)
graph1.insertEdge(6,7)
graph1.insertEdge(6,3)
graph1.insertEdge(6,0)
graph1.insertEdge(7,4)
graph1.insertEdge(0,7)
graph1.insertEdge(0,5)
graph1.insertEdge(2,7)
graph1.insertEdge(3,7)

graph1.printAdjList()
maxDeg , maxVertex = maximum_degree(graph1)
print(f"The vertex {maxVertex} has maximum degree and it is {maxDeg}")

0: -> 5 (W: 1) -> 7 (W: 1) -> 6 (W: 1) -> 1 (W: 1) 
1: -> 5 (W: 1) -> 4 (W: 1) -> 3 (W: 1) -> 2 (W: 1) -> 0 (W: 1) 
2: -> 7 (W: 1) -> 4 (W: 1) -> 3 (W: 1) -> 1 (W: 1) 
3: -> 7 (W: 1) -> 6 (W: 1) -> 4 (W: 1) -> 2 (W: 1) -> 1 (W: 1) 
4: -> 7 (W: 1) -> 6 (W: 1) -> 3 (W: 1) -> 2 (W: 1) -> 1 (W: 1) 
5: -> 0 (W: 1) -> 7 (W: 1) -> 1 (W: 1) 
6: -> 0 (W: 1) -> 3 (W: 1) -> 7 (W: 1) -> 4 (W: 1) 
7: -> 3 (W: 1) -> 2 (W: 1) -> 0 (W: 1) -> 4 (W: 1) -> 6 (W: 1) -> 5 (W: 1) 
The vertex 7 has maximum degree and it is 6


<h1 align = "center">Task 02</h1>

<h1 align = "center">Graph</h1>

![Task 02](https://i.ibb.co.com/KmrVP2R/graph-1.png)

<h1 align = "center">Adjacency Matrix</h1>

In [6]:
def maximum_edge_weight_with_matrix(graph_01):
    maximum = -float('inf')
    idx = -1
    for index in range(graph_01.no_of_vertex):
        weight = graph_01.getWeight(index)
        if weight > maximum :
            maximum = weight
            idx = index
    return idx
test_case = graph(9, False)

test_case.insertEdge(0, 2, 10)
test_case.insertEdge(0, 1, 65)
test_case.insertEdge(0, 8, 50)
test_case.insertEdge(1, 2, 1)
test_case.insertEdge(1, 4, 60)
test_case.insertEdge(1, 7, 70)
test_case.insertEdge(1, 8, 5)
test_case.insertEdge(2, 6, 15)
test_case.insertEdge(2, 3, 90)
test_case.insertEdge(3, 5, 75)
test_case.insertEdge(3, 4, 30)
test_case.insertEdge(3, 7, 35)
test_case.insertEdge(4, 6, 20)
test_case.insertEdge(4, 5, 25)
test_case.insertEdge(5, 6, 85)
test_case.insertEdge(5, 7, 40)

print(test_case.adjacency_matrix)
print(f"Vertex {maximum_edge_weight_with_matrix(test_case)} has maximum sum of edge weights")

[[ 0 65 10  0  0  0  0  0 50]
 [65  0  1  0 60  0  0 70  5]
 [10  1  0 90  0  0 15  0  0]
 [ 0  0 90  0 30 75  0 35  0]
 [ 0 60  0 30  0 25 20  0  0]
 [ 0  0  0 75 25  0 85 40  0]
 [ 0  0 15  0 20 85  0  0  0]
 [ 0 70  0 35  0 40  0  0  0]
 [50  5  0  0  0  0  0  0  0]]
Vertex 3 has maximum sum of edge weights


<h1 align = "center">Adjacency List</h1>

In [7]:
def maximum_edge_weight_with_list(graph_01):
    sumA = np.full(graph_01.no_of_vertex, 0, dtype=int)
    for index in range(graph_01.no_of_vertex):
        sum = 0
        temp = graph_01.vertex_list[index]
        while temp != None :
            sum += temp.weight
            temp = temp.next
        sumA[index] = sum
    maximum = -float('inf')
    for index in range(sumA.size) :
        if sumA[index] > maximum :
            maximum = sumA[index]
            maxVertex = index
    return maxVertex

test_case = LinkedList(9, False)

test_case.insertEdge(0, 2, 10)
test_case.insertEdge(0, 1, 65)
test_case.insertEdge(0, 8, 50)
test_case.insertEdge(1, 2, 1)
test_case.insertEdge(1, 4, 60)
test_case.insertEdge(1, 7, 70)
test_case.insertEdge(1, 8, 5)
test_case.insertEdge(2, 6, 15)
test_case.insertEdge(2, 3, 90)
test_case.insertEdge(3, 5, 75)
test_case.insertEdge(3, 4, 30)
test_case.insertEdge(3, 7, 35)
test_case.insertEdge(4, 6, 20)
test_case.insertEdge(4, 5, 25)
test_case.insertEdge(5, 6, 85)
test_case.insertEdge(5, 7, 40)

test_case.printAdjList()
print(f"\nSum of edge weights of the vertex {maximum_edge_weight_with_list(test_case)} is maximum")

0: -> 8 (W: 50) -> 1 (W: 65) -> 2 (W: 10) 
1: -> 8 (W: 5) -> 7 (W: 70) -> 4 (W: 60) -> 2 (W: 1) -> 0 (W: 65) 
2: -> 3 (W: 90) -> 6 (W: 15) -> 1 (W: 1) -> 0 (W: 10) 
3: -> 7 (W: 35) -> 4 (W: 30) -> 5 (W: 75) -> 2 (W: 90) 
4: -> 5 (W: 25) -> 6 (W: 20) -> 3 (W: 30) -> 1 (W: 60) 
5: -> 7 (W: 40) -> 6 (W: 85) -> 4 (W: 25) -> 3 (W: 75) 
6: -> 5 (W: 85) -> 4 (W: 20) -> 2 (W: 15) 
7: -> 5 (W: 40) -> 3 (W: 35) -> 1 (W: 70) 
8: -> 1 (W: 5) -> 0 (W: 50) 

Sum of edge weights of the vertex 3 is maximum


<h1 align = "center">Task 03</h1>

<h1 align = "center">Graph</h1>

![Task 03](https://i.ibb.co.com/nrvvNWs/graph.png)

<h1 align = "center">Adjacency Matrix</h1>

In [8]:
# In case of Directed, edge weighted graph
test_case = graph(9, True)

test_case.insertEdge(4, 6, 20)
test_case.insertEdge(5, 4, 25)
test_case.insertEdge(5, 6, 85)
test_case.insertEdge(0, 1, 65)
test_case.insertEdge(2, 3, 90)
test_case.insertEdge(3, 5, 75)
test_case.insertEdge(1, 4, 60)
test_case.insertEdge(1, 2, 55)
test_case.insertEdge(2, 0, 10)
test_case.insertEdge(6, 2, 15)
test_case.insertEdge(1, 7, 70)
test_case.insertEdge(5, 7, 40)
test_case.insertEdge(3, 7, 35)
test_case.insertEdge(4, 3, 30)
test_case.insertEdge(8, 1, 45)
test_case.insertEdge(0, 8, 50)

print(test_case.adjacency_matrix)

maxDeg, maxVertex  = maximum_degree(test_case)
print(f"The vertex {maxVertex} has maximum outdegree and it is {maxDeg}")
print(f"Sum of outgoing edge weights of the vertex {maximum_edge_weight_with_matrix(test_case)} is maximum")

[[ 0 65  0  0  0  0  0  0 50]
 [ 0  0 55  0 60  0  0 70  0]
 [10  0  0 90  0  0  0  0  0]
 [ 0  0  0  0  0 75  0 35  0]
 [ 0  0  0 30  0  0 20  0  0]
 [ 0  0  0  0 25  0 85 40  0]
 [ 0  0 15  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0 45  0  0  0  0  0  0  0]]
The vertex 1 has maximum outdegree and it is 3
Sum of outgoing edge weights of the vertex 1 is maximum


<h1 align = "center">Adjacency List</h1>

In [9]:
test_case = LinkedList(9, True)

test_case.insertEdge(4, 6, 20)
test_case.insertEdge(5, 4, 25)
test_case.insertEdge(5, 6, 85)
test_case.insertEdge(0, 1, 65)
test_case.insertEdge(2, 3, 90)
test_case.insertEdge(3, 5, 75)
test_case.insertEdge(1, 4, 60)
test_case.insertEdge(1, 2, 55)
test_case.insertEdge(2, 0, 10)
test_case.insertEdge(6, 2, 15)
test_case.insertEdge(1, 7, 70)
test_case.insertEdge(5, 7, 40)
test_case.insertEdge(3, 7, 35)
test_case.insertEdge(4, 3, 30)
test_case.insertEdge(8, 1, 45)
test_case.insertEdge(0, 8, 50)
test_case.printAdjList()
maxDeg, maxVertex  = maximum_degree(test_case)
print(f"The maximum outdegree is {maxDeg}")
print(f"Sum of outgoing edge weights of the vertex {maximum_edge_weight_with_list(test_case)} is maximum")

0: -> 8 (W: 50) -> 1 (W: 65) 
1: -> 7 (W: 70) -> 2 (W: 55) -> 4 (W: 60) 
2: -> 0 (W: 10) -> 3 (W: 90) 
3: -> 7 (W: 35) -> 5 (W: 75) 
4: -> 3 (W: 30) -> 6 (W: 20) 
5: -> 7 (W: 40) -> 6 (W: 85) -> 4 (W: 25) 
6: -> 2 (W: 15) 
7: 
8: -> 1 (W: 45) 
The maximum outdegree is 3
Sum of outgoing edge weights of the vertex 1 is maximum


<h1 align = "center">Task 04
</h1>

<h1 align = "center">Graph</h1>

![Task 04](https://i.ibb.co.com/bKWtGfx/graph-2.png)

<h1 align = "center">Adjacency Matrix</h1>

In [12]:
def directed_to_undirected(graph_01):
    for index in range(graph_01.no_of_vertex):
        for index1 in range(graph_01.no_of_vertex) :
            if graph_01.adjacency_matrix[index][index1] != 0:
                graph_01.adjacency_matrix[index1][index] = graph_01.adjacency_matrix[index][index1]
    return graph_01
# Driver Code 4.1
test_case = graph(9, True)

test_case.insertEdge(4, 6, 20)
test_case.insertEdge(5, 4, 25)
test_case.insertEdge(5, 6, 85)
test_case.insertEdge(0, 1, 65)
test_case.insertEdge(2, 3, 90)
test_case.insertEdge(3, 5, 75)
test_case.insertEdge(1, 4, 60)
test_case.insertEdge(1, 2, 55)
test_case.insertEdge(2, 0, 10)
test_case.insertEdge(6, 2, 15)
test_case.insertEdge(1, 7, 70)
test_case.insertEdge(5, 7, 40)
test_case.insertEdge(3, 7, 35)
test_case.insertEdge(4, 3, 30)
test_case.insertEdge(8, 1, 45)
test_case.insertEdge(0, 8, 50)

print("Directed weighted graph:")
print(test_case.adjacency_matrix)
directed_to_undirected(test_case)
print("\nConverted undirected weighted graph:")
print(test_case.adjacency_matrix)

Directed weighted graph:
[[ 0 65  0  0  0  0  0  0 50]
 [ 0  0 55  0 60  0  0 70  0]
 [10  0  0 90  0  0  0  0  0]
 [ 0  0  0  0  0 75  0 35  0]
 [ 0  0  0 30  0  0 20  0  0]
 [ 0  0  0  0 25  0 85 40  0]
 [ 0  0 15  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0 45  0  0  0  0  0  0  0]]

Converted undirected weighted graph:
[[ 0 65 10  0  0  0  0  0 50]
 [65  0 55  0 60  0  0 70 45]
 [10 55  0 90  0  0 15  0  0]
 [ 0  0 90  0 30 75  0 35  0]
 [ 0 60  0 30  0 25 20  0  0]
 [ 0  0  0 75 25  0 85 40  0]
 [ 0  0 15  0 20 85  0  0  0]
 [ 0 70  0 35  0 40  0  0  0]
 [50 45  0  0  0  0  0  0  0]]


In [13]:
def directed_to_undirected(graph_01): 
    for index in range(graph_01.no_of_vertex) :
        temp = graph_01.vertex_list[index]
        while temp != None :
            graph_01.insertEdge(temp.destination, temp.source, temp.weight)
            temp = temp.next
test_case = LinkedList(9, True)

test_case.insertEdge(4, 6, 20)
test_case.insertEdge(5, 4, 25)
test_case.insertEdge(5, 6, 85)
test_case.insertEdge(0, 1, 65)
test_case.insertEdge(2, 3, 90)
test_case.insertEdge(3, 5, 75)
test_case.insertEdge(1, 4, 60)
test_case.insertEdge(1, 2, 55)
test_case.insertEdge(2, 0, 10)
test_case.insertEdge(6, 2, 15)
test_case.insertEdge(1, 7, 70)
test_case.insertEdge(5, 7, 40)
test_case.insertEdge(3, 7, 35)
test_case.insertEdge(4, 3, 30)
test_case.insertEdge(8, 1, 45)
test_case.insertEdge(0, 8, 50)

print("Directed weighted graph:")
test_case.printAdjList()
directed_to_undirected(test_case)
print("\nConverted undirected weighted graph:")
test_case.printAdjList()

Directed weighted graph:
0: -> 8 (W: 50) -> 1 (W: 65) 
1: -> 7 (W: 70) -> 2 (W: 55) -> 4 (W: 60) 
2: -> 0 (W: 10) -> 3 (W: 90) 
3: -> 7 (W: 35) -> 5 (W: 75) 
4: -> 3 (W: 30) -> 6 (W: 20) 
5: -> 7 (W: 40) -> 6 (W: 85) -> 4 (W: 25) 
6: -> 2 (W: 15) 
7: 
8: -> 1 (W: 45) 

Converted undirected weighted graph:
0: -> 2 (W: 10) -> 8 (W: 50) -> 1 (W: 65) 
1: -> 8 (W: 45) -> 0 (W: 65) -> 7 (W: 70) -> 2 (W: 55) -> 4 (W: 60) 
2: -> 6 (W: 15) -> 1 (W: 55) -> 0 (W: 10) -> 3 (W: 90) 
3: -> 4 (W: 30) -> 2 (W: 90) -> 7 (W: 35) -> 5 (W: 75) 
4: -> 5 (W: 25) -> 1 (W: 60) -> 3 (W: 30) -> 6 (W: 20) 
5: -> 3 (W: 75) -> 7 (W: 40) -> 6 (W: 85) -> 4 (W: 25) 
6: -> 5 (W: 85) -> 4 (W: 20) -> 2 (W: 15) 
7: -> 5 (W: 40) -> 3 (W: 35) -> 1 (W: 70) 
8: -> 0 (W: 50) -> 1 (W: 45) 
